CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users OWNER TO hriddu;
ALTER TABLE credit_applications OWNER TO hriddu;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hriddu;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hriddu;